# Este es un archivo de flujo de trabajo de GitHub Actions (work_1.yml)
# Aquí puedes definir los jobs y pasos para automatizar tareas en tu repositorio.

name: my-sql-test
on:
  push:
    branches:
      - test_1
jobs: 
    build:
        runs-on: ubuntu-latest
        container: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        steps:
        - name: version
          run: mysql --version
        - name: impresion1
          run: echo "Hola holaaa, soy Andy!"
        - name: impresion2
          run: echo "Impresión 2!"
        - name: impresion3
          run: echo "Impresión 3!"